---
title: "Aphid shoot"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(stringr)
library(readxl)
library(readr)
library(lubridate)
library(patchwork)
```



```{r include=FALSE}
##Aphid infected shoots##

#Loading dataset for aphid infected shoots 
aphid_infected_shoot <- read_excel("data/Aphid_shoot_trial1.xlsx")


#Dataframe for frass spray application experiment
spray_frass.df <- aphid_infected_shoot %>% 
  filter(experiment %in% c('felles', '2a'))

#Dataframe for frass in soil experiment
frass_soil.df <- aphid_infected_shoot %>% 
  filter(experiment %in% c('felles', '2b'))
```



```{r include=FALSE}

#Making dataframe of each date measured. Filtering out treatment 3 since this is the control for experiment 2b.

aphid_shoot_spray1.df <- spray_frass.df %>%
  filter(!behandling == 3) %>% 
    select(Trenummer,behandling,`Aphid_16/06`) %>% 
    group_by(behandling)

aphid_shoot_spray2.df <- spray_frass.df %>%
  filter(!behandling == 3) %>% 
    select(Trenummer,behandling, `Aphid_ 23/06`) %>% 
    group_by(behandling)

aphid_shoot_spray3.df <- spray_frass.df %>%
  filter(!behandling == 3) %>% 
    select(Trenummer,behandling, `Aphid_30/06`) %>% 
    group_by(behandling)

aphid_shoot_spray4.df <- spray_frass.df %>%
  filter(!behandling == 3) %>% 
    select(Trenummer,behandling, `Aphid_07/07`) %>% 
    group_by(behandling)
```

```{r echo=FALSE, warning=FALSE}
#Making dataframe of each date measured. Filtering out treatment 2 since this is the control for experiment 2a.

frass_soil_shoot1.df <- frass_soil.df %>%
  filter(!behandling == 2) %>% 
    select(Trenummer,behandling,`Aphid_16/06`) %>% 
    group_by(behandling)

frass_soil_shoot2.df <- frass_soil.df %>%
  filter(!behandling == 2) %>% 
    select(Trenummer,behandling, `Aphid_ 23/06`) %>% 
    group_by(behandling)

frass_soil_shoot3.df <- frass_soil.df %>%
  filter(!behandling == 2) %>% 
    select(Trenummer,behandling, `Aphid_30/06`) %>% 
    group_by(behandling)

frass_soil_shoot4.df <- frass_soil.df %>%
  filter(!behandling == 2) %>% 
    select(Trenummer,behandling, `Aphid_07/07`) %>% 
    group_by(behandling)
```



```{r echo = FALSE, warning=FALSE}

#Making simple boxplots for visualisation for spray application experiment

 p1 <- ggplot(aphid_shoot_spray1.df) +
  aes(x = behandling, y = `Aphid_16/06`) +
  geom_boxplot() +
  scale_color_hue(direction = 1) +
  labs(
    x = "Treatment",
    y = "Aphid shoots",
    title = "Sprayed Aphid shoots 16/06"
  ) +
   theme_minimal()

 p2 <- ggplot(aphid_shoot_spray2.df) +
  aes(x = behandling, y = `Aphid_ 23/06`
      ) +
  geom_boxplot() +
  scale_color_hue(direction = 1) +
  labs(
    x = "Treatment",
    y = "Aphid shoots",
    title = "Sprayed Aphid shoots 23/06"
  ) +
  theme_minimal()


 p3 <- ggplot(aphid_shoot_spray3.df) +
  aes(x = behandling, y = `Aphid_30/06`
      ) +
  geom_boxplot() +
  scale_color_hue(direction = 1) +
  labs(
    x = "Treatment",
    y = "Aphid shoots",
    title = "Sprayed Aphid shoots 30/06"
  ) +
  theme_minimal()

 p4 <- ggplot(aphid_shoot_spray4.df) +
  aes(x = behandling, y = `Aphid_07/07`
      ) +
  geom_boxplot() +
  scale_color_hue(direction = 1) +
  labs(
    x = "Treatment",
    y = "Aphid shoots",
    title = "Sprayed Aphid shoots 07/07"
  ) +
  theme_minimal()


 p1 + p2 + p3 + p4

```



```{r echo = FALSE, warning=FALSE}
#Making simple boxplots for visualisation for frass in soil experiment

 s1 <- ggplot(frass_soil_shoot1.df) +
  aes(x = behandling, y = `Aphid_16/06`) +
  geom_boxplot() +
  scale_color_hue(direction = 1) +
  labs(
    x = "Treatment",
    y = "Aphid shoots",
    title = "Soil Aphid shoots 16/06"
  ) +
   theme_minimal()

 s2 <- ggplot(frass_soil_shoot2.df) +
  aes(x = behandling, y = `Aphid_ 23/06`
      ) +
  geom_boxplot() +
  scale_color_hue(direction = 1) +
  labs(
    x = "Treatment",
    y = "Aphid shoots",
    title = "Soil Aphid shoots 23/06"
  ) +
  theme_minimal()


 s3 <- ggplot(frass_soil_shoot3.df) +
  aes(x = behandling, y = `Aphid_30/06`
      ) +
  geom_boxplot() +
  scale_color_hue(direction = 1) +
  labs(
    x = "Treatment",
    y = "Aphid shoots",
    title = "Soil Aphid shoots 30/06"
  ) +
  theme_minimal()

 s4 <- ggplot(frass_soil_shoot4.df) +
  aes(x = behandling, y = `Aphid_07/07`
      ) +
  geom_boxplot() +
  scale_color_hue(direction = 1) +
  labs(
    x = "Treatment",
    y = "Aphid shoots",
    title = "Soil Aphid shoots 07/07"
  ) +
  theme_minimal()

 s1 + s2 + s3 + s4

```

##Aphid shoot length##

```{r include=FALSE}
##Aphid shoot length##

#Loading dataset for aphid shoot length
aphid_shoot_length <- read_excel("data/Shoot_length.xlsx")


#Dataframe for shoot length in frass spray application experiment
shoot_length_spray.df <- aphid_shoot_length %>% 
  filter(experiment %in% c('felles', '2a'))

#Dataframe for shoot length in frass in soil experiment
frass_length_soil.df <- aphid_shoot_length %>% 
  filter(experiment %in% c('felles', '2b'))


```

```{r include=FALSE}

#Making dataframe of each date measured. Filtering out treatment 3 since this is the control for experiment 2b.

frass_spray_shoot_length1.df <- shoot_length_spray.df %>%
  filter(!behandling == 3) %>% 
    select(behandling,`Shoot_length_01-04/6`) %>% 
    group_by(behandling)

frass_spray_shoot_length2.df <- shoot_length_spray.df %>%
  filter(!behandling == 3) %>% 
    select(behandling,`Shoot_length_18/6`) %>% 
    group_by(behandling)

frass_spray_shoot_length3.df <- shoot_length_spray.df %>%
  filter(!behandling == 3) %>% 
    select(behandling,`Shoot_length_09/7`) %>% 
    group_by(behandling)


```

```{r echo = FALSE, warning=FALSE}
#Making simple boxplots for visualisation for shoot length in spray application

lp1 <- ggplot(frass_spray_shoot_length1.df) +
  aes(x = behandling, y = `Shoot_length_01-04/6`) +
  geom_boxplot() +
  scale_color_hue(direction = 1) +
  labs(
    x = "Treatment",
    y = "Shoot length",
    title = "Spray shoot length 01/06"
  ) +
   theme_minimal()

lp2 <-  ggplot(frass_spray_shoot_length2.df) +
  aes(x = behandling, y = `Shoot_length_18/6`) +
  geom_boxplot() +
  scale_color_hue(direction = 1) +
  labs(
    x = "Treatment",
    y = "Shoot length",
    title = "Spray shoot length 18/06"
  ) +
   theme_minimal()
 
lp3 <- ggplot(frass_spray_shoot_length3.df) +
  aes(x = behandling, y = `Shoot_length_09/7`) +
  geom_boxplot() +
  scale_color_hue(direction = 1) +
  labs(
    x = "Treatment",
    y = "Shoot length",
    title = "Spray shoot length 09/07"
  ) +
   theme_minimal()

lp1 + lp2 + lp3
```



```{r include=FALSE}

#Making dataframe of each date measured. Filtering out treatment 2 since this is the control for experiment 2a.

frass_soil_shoot_length1.df <- frass_length_soil.df %>%
  filter(!behandling == 2) %>% 
    select(behandling,`Shoot_length_01-04/6`) %>% 
    group_by(behandling)

frass_soil_shoot_length2.df <- frass_length_soil.df %>%
  filter(!behandling == 2) %>% 
    select(behandling,`Shoot_length_18/6`) %>% 
    group_by(behandling)

frass_soil_shoot_length3.df <- frass_length_soil.df %>%
  filter(!behandling == 2) %>% 
    select(behandling,`Shoot_length_09/7`) %>% 
    group_by(behandling)
```


```{r echo = FALSE, warning=FALSE}
#Making simple boxplots for visualisation for shoot length in frass in soil

ls1 <-ggplot(frass_soil_shoot_length1.df) +
  aes(x = behandling, y = `Shoot_length_01-04/6`) +
  geom_boxplot() +
  scale_color_hue(direction = 1) +
  labs(
    x = "Treatment",
    y = "Shoot length",
    title = "Soil shoot length 01/06"
  ) +
   theme_minimal()

ls2 <- ggplot(frass_soil_shoot_length2.df) +
  aes(x = behandling, y = `Shoot_length_18/6`) +
  geom_boxplot() +
  scale_color_hue(direction = 1) +
  labs(
    x = "Treatment",
    y = "Shoot length",
    title = "Soil shoot length 18/06"
  ) +
   theme_minimal()
 
ls3 <- ggplot(frass_soil_shoot_length3.df) +
  aes(x = behandling, y = `Shoot_length_09/7`) +
  geom_boxplot() +
  scale_color_hue(direction = 1) +
  labs(
    x = "Treatment",
    y = "Shoot length",
    title = "Soil shoot length 09/07"
  ) +
   theme_minimal()

ls1 + ls2 + ls3
```

